### PR TITLE
my side of the story

### PR DESCRIPTION
**Pull request by Nathaly3162**

### CODE REVIEW

**Comment by floridop** [comment]
Hi! The fact that there is already a conflict in this PR makes me think there's still something wrong in the status of your git...

However, here's how to carry on the exercise:
Unfortunately it seems that there were changes in the main that conflict with yours. 
Could you please perform a merge as described in Tutorial 3 slides 90-103 and integrate those changes?
Start with synchronizing your local main with my upstream main as described in slide 98.
We do not want to lose any existing content, so you should keep what others have written and add yours.
You're free to reorganize the content blocks so that it still makes a story, but please do minimal changes
to the content of what others have written to integrate them with yours. 
The merges will be approved according to arrival time starting from October 23th, 22:00, 
so expect that you need to merge several times after that time.
If I do not approve the changes you will be asked to update the content.

**Comment by Nathaly3162** [comment]
Hello

I was wondering, as I have 4/5 points as of right now. Is that a passing
grade? if it is, I think I am willing to give up on the last part at this
point.

**Comment by floridop** [comment]
Hi
It is a passing grade.
Sorry to hear that you give up. It's not that difficult nor time consuming.

**Comment by floridop** [comment]
Closing as user decided not to complete.

**Pull request closed without merging**
