### PR TITLE
my side of the story

### PR DESCRIPTION
**Pull request by simgor1**

### CODE REVIEW

**Comment by floridop** [comment]
Hi! Thanks for your submission.

Unfortunately it seems that there were changes in the main that conflict with yours. 
Could you please perform a merge as described in Tutorial 3 slides 90-103 and integrate those changes?
Start with synchronizing your local main with my upstream main as described in slide 98.
We do not want to lose any existing content, so you should keep what others have written and add yours.
You're free to reorganize the content blocks so that it still makes a story, but please do minimal changes
to the content of what others have written to integrate them with yours. 
You have time until the **20th of October at 23:59**. 
If you can't make it by that time or you are done before the deadline, 
please add a comment in github so that I can progress with another student.

**Comment by simgor1** [comment]
Hi!
I'm so sorry i completely missed the comment you left. Is it too late for me to do the changes now?
Best regards Simon

**Comment by floridop** [comment]
Hi Simon, yes you can go ahead and perform the merge but if one of your colleagues is faster than you, you might have to do it again, as we are entering the last week of course and I want to give everyone a chance.

**Comment by simgor1** [comment]
Alright I did it now hope everything works :)

**Comment by floridop** [comment]
Hi Simon, 
I think what you did worked, but in a collaborative environment things change very quickly. Some of your colleagues where faster and now there are new conflicts due to changes you colleagues did (you can see the closed pull request timeline to verify my claims).
This is the main reason for which I allocate some time for each student, so that they have time to merge before other changes come to be.
My suggestion is that you do another merge, and actually I liked your line as it introduced some plot twist, I would recommend that you find a spot in the new story to add it again.

**Comment by floridop** [comment]
Thanks for your contribution! Task 2 completed! See canvas for results

**Pull request merged**
