### PR TITLE
my side of the story

### PR DESCRIPTION
**Pull request by wiederk**

### CODE REVIEW

**Comment by floridop** [comment]
Hi! Thanks for your submission.

Unfortunately it seems that there were changes in the main that conflict with yours. 
Could you please perform a merge as described in Tutorial 3 slides 90-103 and integrate those changes?
Start with synchronizing your local main with my upstream main as described in slide 98.
We do not want to lose any existing content, so you should keep what others have written and add yours.
You're free to reorganize the content blocks so that it still makes a story, but please do minimal changes
to the content of what others have written to integrate them with yours. 
The merges will be approved according to arrival time starting from October 23th, 22:00, 
so expect that you need to merge several times after that time.
If I do not approve the changes you will be asked to update the content.

**Comment by wiederk** [comment]
Hello,
I received an Email saying there was a problem with my merge and you started a review, which i should take a look at. However, GitHub here still states that the branch has no conflicts with the base branch. So it should be ready to merge?

**Comment by floridop** [comment]
Hi @wiederk 

As a release manager I am supposed to check that both 1) the merge is ok (it looks ok so far) and 2) the contents of the merge are acceptable. 

I started a review because I won't merge to my main until the suggested contribution is in line with what I want, that is, the line I mentioned in the review should appear after a newline. Please follow the instructions in the review to complete this task.

**Comment by wiederk** [comment]
Hi @floridop 
Thanks for the clarification! 

This might sound stupid, but where can I see the review? In the top right of this pull request, it still says "No reviews" under Reviewers...
Thanks in Advance!

**Comment by floridop** [comment]
Hi! 
> where can I see the review? 

The review might be seen in this conversation or by clicking on "Files changed"
For your convenience here's a link: <https://github.com/floridop/MNXB11-fairytale/pull/97/files>

While we were discussing, as it happens in a distributed collaborative environment things change very quickly. Some of your colleagues where faster and now there are new conflicts due to changes you colleagues made (you can see the closed pull request timeline to verify my claims).
This is the main reason for which I allocate some time for each student, so that they have time to merge before other changes come to be. Unfortunately if it is many students we don't always manage to be fair.
My suggestion is that you do another merge (another iteration of slides 90-103) and fix the requested line when you do it.
This is pretty much what happens in real life big projects.

**Comment by floridop** [comment]
Thanks for your contribution! Task 2 completed! See canvas for results

**Pull request merged**
