### PR TITLE
Mystory

### PR DESCRIPTION
**Pull request by msitor7**

### CODE REVIEW

**Comment by msitor7** [comment]
my side of the story

**Comment by floridop** [comment]
Hi
Just FYI, if you don't submit to canvas, I cannot grade you. If you are not interested in grading I can interact with you to learn git.
It seems that you submitted your pull request from your _mystory_ branch to my _mystory_ branch, but you should request me to pull your _mystory_ branch into my **main** branch instead, as described in slides 72 and 73.
I will close this PR, you need to reopen another one against the right branch.

**Comment by msitor7** [comment]
Hi,

Okay I will try to do it again, also I am having some problems to push the
repository to my own branch in homework4, I am trying to do it to send you
my HTTPS:// URL  but this is what its says;

***@***.*** code]$ git push origin homework4
Username for 'https://github.com': msitor7
Password for ***@***.***':
remote: Permission to floridop/MNXB11-BASH.git denied to msitor7.
fatal: unable to access 'https://github.com/floridop/MNXB11-BASH.git/': The
requested URL returned error: 403
***@***.*** code]$

If there is another way of doing it, let me know

Thank you,

**Comment by floridop** [comment]
Hi
I think it's best that you pass by office next week, for what I see there are couple of things that are not clear for you, I will try to clarify.

Here's some pieces of it based on what you sent:
>remote: Permission to floridop/MNXB11-BASH.git denied to msitor7.
fatal: unable to access 'https://github.com/floridop/MNXB11-BASH.git/': The
requested URL returned error: 403
***@***.*** code]$

You are trying to push changes to my `MNXB11-BASH` repository but you cannot push to my repository. You are supposed to copy the code over to your MNXB11-homework personal repository. This is described in the homework README.md:
https://github.com/floridop/MNXB11-BASH/tree/main/homework4#how-to-proceed

You should do all the homeworks on yuur MNXB11-homework repository and share with us links to your repositories to the homework you did.
I think you should visit me in my office during next week, explaining this in a text will not bring us forward.

**Comment by msitor7** [comment]
Hi,

I saw where the problem was, but still maybe I can pass by your office on
friday if you are okay with that.

Thank you,

**Comment by floridop** [comment]
> pass by your office on friday if you are okay with that.
Sure! see you. I should be there from 10:00 on. More details only via work email.

**Pull request closed without merging**
