### PR TITLE
my side of the story

### PR DESCRIPTION
**Pull request by Nathaly3162**

### CODE REVIEW

**Comment by floridop** [comment]
Hi! Thanks for your submission.

Unfortunately it seems that there were changes in the main that conflict with yours. 
Could you please perform a merge as described in Tutorial 3 slides 90-103 and integrate those changes?
Start with synchronizing your local main with my upstream main as described in slide 98.
We do not want to lose any existing content, so you should keep what others have written and add yours.
You're free to reorganize the content blocks so that it still makes a story, but please do minimal changes
to the content of what others have written to integrate them with yours. 
The merges will be approved according to arrival time starting from October 23th, 22:00, 
so expect that you need to merge several times after that time.
If I do not approve the changes you will be asked to update the content.

**Comment by Nathaly3162** [comment]
Hello,

Everything says that everything is up to date. I went through the slides
and followed the instructions but all the commands gave back that "all is
up to date".

**Comment by floridop** [comment]
Hi Nathaly
I suspect you did not add my upstream. By looking at your main, it is very outdated compared to mine. That means your **origin** __main__ is not in sync with my **upstream** __main__
In this git flow model, you have to make sure your **origin** __main__ is always a copy of my **upstream** __main__ before merging.
  - Properly setting up my upstream main is described in slide 74
  - Synchronizing your origin and my upstream main is described in slide 94

A common problem is that you may have selected the wring **upstream** URL, for example using the same one as your **origin**.  git is not smart to identify this. For example, what do you see when you run:
```console
git remote -v
```
You should see something like this:
```console
origin	git@github.com:Nathaly3162/MNXB11-fairytale.git (fetch)
origin	git@github.com:Nathaly3162/MNXB11-fairytale.git (push)
upstream	https://github.com/floridop/MNXB11-fairytale.git (fetch)
upstream	https://github.com/floridop/MNXB11-fairytale.git (push)
```

**Comment by Nathaly3162** [comment]
Hey
when I run git remote -v that's exactly what I see, the remote upstream
already exists and even when I did all that's in slide 94 it said
everything is up to date. I don't know what to do

**Comment by floridop** [comment]
Ok, let's assume that everything is up-to-date.

Then what happens if you follow slides 97-102?

**Pull request closed without merging**
